### ISSUE TITLE
I can't reset changes in file

### ISSUE THREAD

**Issue by ngoclt1499** [RubyBarSchool/GIT#3]
I don't understand delete all change in one file after add to stagging area

**Comment by RubyBarSchool** [comment]
oh, i thick you can follow these steps
B1: You should understand GIT RESTORE 
usage: git restore [<options>] [--source=<branch>] <file>...

    -s, --source <tree-ish>
                          which tree-ish to checkout from
    -S, --staged          restore the index
    -W, --worktree        restore the working tree (default)
    --ignore-unmerged     ignore unmerged entries
    --overlay             use overlay mode
    -q, --quiet           suppress progress reporting
    --recurse-submodules[=<checkout>]
                          control recursive updating of submodules
    --progress            force progress reporting
    -m, --merge           perform a 3-way merge with the new branch
    --conflict <style>    conflict style (merge, diff3, or zdiff3)
    -2, --ours            checkout our version for unmerged files
    -3, --theirs          checkout their version for unmerged files
    -p, --patch           select hunks interactively
    --ignore-skip-worktree-bits
                          do not limit pathspecs to sparse entries only
    --pathspec-from-file <file>
                          read pathspec from file
    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character

git restore --staged  <file>: restore the index


B2: git restore <file> : restore all change in file

**Comment by ngoclt1499** [comment]
Oh, thanks you. It work

**Comment by RubyBarSchool** [comment]
That's also my question when I started to learn git. 

You can use command   git .... --help
you can see the syntax of git commands and how to use them

**Comment by NgocLT14071998** [comment]
- git reset HEAD <file>
- git checkout -- <file>
